name: kukisense_intesis_demo
description: Kukisense + Intesis AC Automation Demo
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  mqtt_client: ^10.0.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
